### ISSUE TITLE
First stable release checklist

### ISSUE THREAD

**Issue by ihaveamac** [ihaveamac/fuse-3ds#14]
I think fuse-3ds is now developed enough for a full stable release. But before I make a release called "1.0", I need all the features to be tested, and on all supported platforms, to make sure no obvious bugs stay in (like they have in the past).

Any help is appreciated! Testing all the features on 3 platforms is a lot of work for one person.

Please test on Python 3.6.5 if possible, which is the latest and is preferred, but 3.6.1+ is supported. If you're on Windows, you can also use the [latest standalone exe in releases](https://github.com/ihaveamac/fuse-3ds/releases).

These platforms are supported:
* Windows (7 SP1, 8.1, 10)
  * If starting from a fresh install...
    * Windows 7 and 8.1 need [Update for Universal C Runtime in Windows](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows) (for standalone executable to work)
    * Windows 7 needs [Microsoft Security Advisory 3033929](https://docs.microsoft.com/en-us/security-updates/SecurityAdvisories/2015/3033929) (for WinFsp driver)
* macOS (El Capitan, Sierra, High Sierra)
  * Older ones may work (tested as low as 10.6 Snow Leopard) but these are my primary focus.
* Linux (any modern one should do)

When posting if a feature works or not, please post the operating system, fuse-3ds version, and (if not standalone exe) Python version used (`py  -3 -VV` or `python3 -VV`).

## Things to try
- Any mount works on...
  - [x] Windows 32-bit (me)
  - [x] Windows 64-bit (me)
  - [x] macOS (me)
  - [x] Linux
    - Arch Linux: @knight-ryu12
- All GUI functions work on...
  - [x] Windows (me)
    - Note that drag&drop doesn't work on 32-bit Python at the moment. Still works in the standalone executable.
    - Windows 7 32-bit: me
    - Windows 7 64-bit: me
    - Windows 10 64-bit: me
  - [x] macOS (me)
  - [x] Linux
    - Arch Linux: @knight-ryu12

#### CCI
  - [x] Files read correctly
    - Windows: me
    - macOS: me
#### CDN
  - [x] Files read correctly
    - Windows: me
    - Ubuntu 18.04: me
  - [x] Works with existing cetk file
    - Windows: me
    - Ubuntu 18.04: me
  - [x] Works with provided titlekey (has priority over cetk if it exists)
    - Windows: me
    - Ubuntu 18.04: me
#### CIA
  - [x] Encrypted files read correctly
    - Arch Linux: @knight-ryu12
    - Windows: me
    - macOS: me
  - [x] Decrypted files read correctly
    - Arch Linux: @knight-ryu12
    - Windows: me
    - macOS: me
#### ExeFS
  - [x] Files read correctly
    - Windows: me
  - [x] Code is decompressed without errors (assuming original .code is not corrupted)
    - Arch Linux: @knight-ryu12
    - Windows: me
#### NAND (3DS & DSi) (remember to use `-o allow_root` or `-o allow_other` on Linux/macOS, and a directory as mount point on Windows)
  - [x] Files read correctly
    - macOS: me
    - Windows: me
  - [x] Writes to existing files works
    - Windows: me
    - macOS: me
  - Mounting FAT partition works on...
    - [x] Windows (try OSFMount) (me)
    - [x] macOS (use hdiutil or double-click from Finder) (me)
    - [x] Linux
      - Arch Linux: @knight-ryu12
  - Writing in FAT partition works on...
    - [x] Windows (me)
    - [x] macOS (me)
    - [x] Linux
      - Arch Linux: @knight-ryu12
#### NCCH
  - [x] Encrypted files read correctly
    - Windows: me
    - macOS: me
  - [x] Zero-key encrypted files read correctly
    - Windows: me
    - macOS: me
  - [x] Decrypted files read correctly
    - Windows: me
    - macOS: me
  - [x] `decrypted.cxi` of encrypted game works with an application that expects a decrypted file
    - macOS: me
    - Windows: me
#### RomFS
  - [x] Files read correctly
    - Windows: me
#### SD
  - [x] Files read correctly
    - macOS: me
    - Windows: me
  - Writes to existing files works on...
    - [x] Windows (me)
    - [x] macOS (me)
      - Changing file size while writing in the middle doesn't work properly: #17
    - [x] Linux
      - Arch Linux: someone else
  - Creating new files works on...
    - [x] Windows (me)
    - [x] macOS (me)
    - [x] Linux
      - Arch Linux: @knight-ryu12
#### 3DSX
  - [x] Files read correctly
    - Windows: me
    - macOS: me
#### Titledir
  - [x] Files read correctly
    - macOS: me
    - Windows: me

**Comment by knight-ryu12** [comment]
python3 -VV
```Python 3.6.5 (default, May 11 2018, 04:00:52) 
[GCC 8.1.0]
```
uname -a
```
Linux luna 4.16.6-1-ARCH #1 SMP PREEMPT Mon Apr 30 12:30:03 UTC 2018 x86_64 GNU/Linux
```
worked Checklist
- GUI
- Any Mount

in regard of mounting in Linux
- CIA Both Dec/Enc
- CIA .code bin decompress

I'll do more test if requested

**Comment by ihaveamac** [comment]
updated original post w/ more results by me and @knight-ryu12

**Comment by ihaveamac** [comment]
only 3 more things need to be tested, all for Linux

**Comment by knight-ryu12** [comment]
will do after I got home

2018年5月28日(月) 8:57 Ian Burgwin <notifications@github.com>:

**Comment by ihaveamac** [comment]
release v1.0b9 is mostly changes that affect all mounts and internal stuff. tested various mounts and they all still worked.

**Comment by ihaveamac** [comment]
DSi NAND mount was added in b299937841338d12619beacaf7a5d6b08176596a, it shares a lot of the same code as 3DS and was tested on windows + mac.

**Comment by ihaveamac** [comment]
Everything confirmed to be working, a stable release can be put out soon.
